# Generated by Django 4.2.4 on 2024-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_valid', models.BooleanField(default=False)),
                ('stay_arrival_date', models.DateTimeField(blank=True, null=True)),
                ('stay_departure_date', models.DateTimeField(blank=True, null=True)),
                ('person_first_name_0', models.CharField(blank=True, max_length=255)),
                ('person_last_name_0', models.CharField(blank=True, max_length=255)),
                ('person_country_0', models.CharField(blank=True, max_length=255)),
                ('person_sex_0', models.CharField(blank=True, max_length=10)),
                ('person_birth_date_0', models.DateTimeField(blank=True, null=True)),
                ('person_first_name_1', models.CharField(blank=True, max_length=255)),
                ('person_last_name_1', models.CharField(blank=True, max_length=255)),
                ('person_country_1', models.CharField(blank=True, max_length=255)),
                ('person_sex_1', models.CharField(blank=True, max_length=10)),
                ('person_birth_date_1', models.DateTimeField(blank=True, null=True)),
                ('person_first_name_2', models.CharField(blank=True, max_length=255)),
                ('person_last_name_2', models.CharField(blank=True, max_length=255)),
                ('person_country_2', models.CharField(blank=True, max_length=255)),
                ('person_sex_2', models.CharField(blank=True, max_length=10)),
                ('person_birth_date_2', models.DateTimeField(blank=True, null=True)),
                ('person_first_name_3', models.CharField(blank=True, max_length=255)),
                ('person_last_name_3', models.CharField(blank=True, max_length=255)),
                ('person_country_3', models.CharField(blank=True, max_length=255)),
                ('person_sex_3', models.CharField(blank=True, max_length=10)),
                ('person_birth_date_3', models.DateTimeField(blank=True, null=True)),
                ('person_first_name_4', models.CharField(blank=True, max_length=255)),
                ('person_last_name_4', models.CharField(blank=True, max_length=255)),
                ('person_country_4', models.CharField(blank=True, max_length=255)),
                ('person_sex_4', models.CharField(blank=True, max_length=10)),
                ('person_birth_date_4', models.DateTimeField(blank=True, null=True)),
                ('addr_street', models.CharField(blank=True, max_length=255)),
                ('addr_valid', models.BooleanField(default=False)),
                ('addr_city', models.CharField(blank=True, max_length=255)),
                ('addr_zip', models.CharField(blank=True, max_length=20)),
                ('addr_country', models.CharField(blank=True, max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=255)),
                ('id_valid', models.BooleanField(default=False)),
                ('id_issue_date', models.DateTimeField(blank=True, null=True)),
                ('id_institution', models.CharField(blank=True, max_length=255)),
                ('id_country', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
            ],
        ),
    ]
