# Generated by Django 4.2.4 on 2024-06-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0002_product_abnb_id_product_abnb_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stay_num_guests',
            new_name='stay_num_of_guests',
        ),
    ]
