# Generated by Django 4.2.4 on 2024-09-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0003_rename_stay_num_guests_product_stay_num_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lfdnr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
