# Generated by Django 4.2.4 on 2025-11-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0004_product_lfdnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stay_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stay_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
