# Generated by Django 4.2.4 on 2025-11-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0005_alter_product_id_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_issue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
