# Generated by Django 4.2.4 on 2025-11-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0006_alter_product_id_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
    ]
