# Generated by Django 4.2.4 on 2025-12-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savetodb', '0007_product_email_product_marketing_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_business',
            field=models.BooleanField(default=False),
        ),
    ]
